### ISSUE TITLE
Create Explicit Measures: What about AggregateFunction.Default ?

### ISSUE THREAD

**Issue by FrankFromGermany** [TabularEditor/Scripts#7]
@tomatminceddata,
is it possible to include the common Default aggregation in this script?
Then we do not have to replace Default by Sum everywhere.
BTW, is there a reason for excluding DistinctCount ?

**Comment by otykier** [comment]
Good suggestions. @tomatminceddata , what do you think?

**Comment by tomatminceddata** [comment]
Hey @FrankFromGermany, @otykier I will add AggregateFunction.Default at the latest until the13th of September (of course this year), allowing to select the aggregate function for different data types.
I consider DISTINCTCOUNT special and due it's nature (and implicit complexity) I do not want to create numerous "expensive" measures instead of using COUNTROWS(VALUES('<tablename>'[columnname]) or optimized methods leveraging COUNTX(...), SUMX(...), or even more fancy stuff. For this I will most likely not include DISTINCTCOUNT :-)

**Comment by tomatminceddata** [comment]
Hey @FrankFromGermany , 
the latest release now support AggregateFunction.Default

**Comment by FrankFromGermany** [comment]
Thanks @tomatminceddata ,
It does mess up the measure list, but IMO it's easier to delete or hide several default measures than to create some manually.
